name: Test API

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Installation
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt install -y git python3 python3-aiohttp sudo acl curl systemd-container
          sudo useradd jailman

      - name: Download Firecracker and Jailer
        run: |
          sudo mkdir /opt/firecracker
          # sudo chown root /opt/firecracker
          sudo curl -fsSL https://github.com/firecracker-microvm/firecracker/releases/download/v0.24.2/firecracker-v0.24.2-x86_64.tgz | tar -xz --directory /opt/firecracker

          # Link binaries on version-agnostic paths:
          sudo ln /opt/firecracker/firecracker-v* /opt/firecracker/firecracker
          sudo ln /opt/firecracker/jailer-v* /opt/firecracker/jailer

      - name: Build the runtime rootfs
        run: |
          pwd
          find .
          cd ./runtimes/aleph-alpine-3.13-python
          sudo bash ./create_disk_image.sh
          # Run it a second time to solve a bug
          sudo bash ./create_disk_image.sh
          cd ../..

      - name: Setup the jailer working directory
        run: |
          sudo mkdir /srv/jailer

      - name: Run the VM Supervisor
        run: |
          sudo pip install pytest pytest-asyncio
          sudo export PYTHONPATH=$(pwd)
          sudo pytest -vv -s
