name: Test API

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Installation
        run: |
          apt update
          apt -y upgrade
          apt install -y git python3 python3-aiohttp sudo acl curl systemd-container
          useradd jailman

      - name: Download Firecracker and Jailer
        run: |
          mkdir /opt/firecracker
          chown $(whoami) /opt/firecracker
          curl -fsSL https://github.com/firecracker-microvm/firecracker/releases/download/v0.24.2/firecracker-v0.24.2-x86_64.tgz | tar -xz --directory /opt/firecracker

          # Link binaries on version-agnostic paths:
          ln /opt/firecracker/firecracker-v* /opt/firecracker/firecracker
          ln /opt/firecracker/jailer-v* /opt/firecracker/jailer

      - name: Build the runtime rootfs
        run: |
          cd ./aleph-vm/runtimes/aleph-alpine-3.13-python
          bash ./create_disk_image.sh
          # Run it a second time to solve a bug
          bash ./create_disk_image.sh
          cd ../..

      - name: Setup the jailer working directory
        run: |
          mkdir /srv/jailer

      - name: Run the VM Supervisor
        run: |
          pip install pytest pytest-asyncio
          export PYTHONPATH=$(pwd)
          pytest -vv -s
